### ISSUE TITLE
test more than just latest Chrome & Firefox

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/pouchdb-hoodie-api#1]

**Comment by zoepage** [comment]
How far do you want to go?
Same as PouchDB support? Would be:
Firefox 29+
Chrome 30+
Safari 5+
Internet Explorer 10+
Opera 21+
Android 4.0+
iOS 7.1+
Windows Phone 8+

**Comment by gr2m** [comment]
Sounds good to me. Want to set it up and start a pull request? Check `.zuul.yml`

**Comment by zoepage** [comment]
+1

**Comment by zoepage** [comment]
Thanks to SL, we're testing now:
Firefox 29+
Chrome 30+
Safari 5+
Internet Explorer 10+
Opera 11+12

@gr2m If there is more, I can do... Tell me. If it's good like that, closing this issue?
