### ISSUE TITLE
Semantic release broken

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/pouchdb-hoodie-api#102]
.. and I really don’t know what is happening. It runs test during `npm run semantic-release` and I don’t get why. And worse: the test fail and it doesn’t make any sense :/ see https://travis-ci.org/hoodiehq/pouchdb-hoodie-api/jobs/104455080#L666

This is blocking our Hoodie tent release, would be great if someone could look into this. When this is done, release a new `hoodie-client` version, then uncomment tests in https://github.com/hoodiehq/hoodie-app-something-tracker/tree/master/test which should be fixed due to https://github.com/hoodiehq/hoodie-client-store/issues/69 & https://github.com/hoodiehq/hoodie-client-store/issues/70

https://github.com/hoodiehq/pouchdb-hoodie-api/issues/102

**Comment by gr2m** [comment]
Also the test command is `standard && npm run test:node`, although I moved `standard` into pretest:
https://github.com/hoodiehq/pouchdb-hoodie-api/blob/master/package.json#L64 ... ?!

**Comment by boennemann** [comment]
It's running the old tests via [cracks](https://github.com/semantic-release/cracks): https://github.com/hoodiehq/pouchdb-hoodie-api/blob/master/package.json#L47 ;)

**Comment by gr2m** [comment]
ahhh funky! What would you recommend? Shall we remove cracks here? It seems that `standard` is breaking here, not actual tests ...

**Comment by Guria** [comment]
If cracks detects fail with previous tests you have to define breking changes section in commit message

**Comment by Guria** [comment]
Actually my personal opinion that cracks should be run as part of tests to be able fail build if detected breaking changes that wasn't defined in commit messages

**Comment by gr2m** [comment]
yeah but there is no breaking change, the syntax checker breaks (`standard`), not actual behavior

**Comment by Guria** [comment]
Then you should disable cracks at lest for one release

**Comment by gr2m** [comment]
I’ve removed crack for now via 54cb96b
