### ISSUE TITLE
[API docs] html tags in description columns should not be escaped 

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/pouchdb-hoodie-api#27]
e.g. http://hoodiehq.github.io/pouchdb-hoodie-api/find-or-add.js.html

**Comment by boennemann** [comment]
there's also a whitespace issue in the footer. trailing whitespace is a bit of a pain in jade :/

**Comment by zoepage** [comment]
@boennemann you mean, whitespace issue with the links or?

**Comment by boennemann** [comment]
@zoepage Yeah exactly. Was mobile when I wrote that and only roughly remembered something is broken ;)

**Comment by zoepage** [comment]
@boennemann cool! I'll take care of it :)

**Comment by gr2m** [comment]
fixed via bc9e010
