### ISSUE TITLE
SauceLabs not currently testing on >IE10 or mobile safari

### ISSUE THREAD

**Issue by lewiscowper** [hoodiehq/pouchdb-hoodie-api#28]
"Test are currently not running on >IE10 and mobile Safari. This is likely an error with the setup and we would be more than happy if you'd want to fix that :)"

**Comment by varjmes** [comment]
This is being worked on in #75 :)

Once we fix it here, we should roll out a plan to make sure all out saucelab tests accross repos are the same, as currently they are not :(

**Comment by NickColley** [comment]
I can look after this if you want.

**Comment by gr2m** [comment]
fixed via https://github.com/hoodiehq/pouchdb-hoodie-api/commit/01a9e23b99ed074d2f37d8836c30acc7362dbc6a
