### ISSUE TITLE
add events

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/pouchdb-hoodie-api#31]
``` js
var db = new PouchDB('dbname')
var api = db.hoodieApi()

api.on('add', function(object, options) {})
api.on('update', function(object, options) {})
api.on('remove', function(object, options) {})
api.on('change', function(eventName, object, options) {})

api.one('add', function(object, options) {})
api.off('add', handler)
```

Events should be implemented using EventEmitter. See [implementation](https://github.com/hoodiehq/wip-hoodie-store-on-pouchdb/blob/master/lib/api.js#L493-L577) / [tests](https://github.com/hoodiehq/wip-hoodie-store-on-pouchdb/blob/master/tests/test.events.js#L15-L257) in https://github.com/hoodiehq/wip-hoodie-store-on-pouchdb
- ignore sync / clear events
- ignore scoping with `storeOptions.type`
- Implementation should not bloat the code for modular usage:

``` js
PouchDB.plugin({
  add: require('pouchdb-hoodie-api/add')
})
```

**Comment by gr2m** [comment]
@patriciagarcia could you add a test, in which a doc gets created in the db before we initiate the api, to make sure that no change event gets triggered for it?

**Comment by patriciagarcia** [comment]
@gr2m, before we initiate the API or before we start listening to events?

**Comment by gr2m** [comment]
excellent good question :) Before listening to events makes sense, it will cover the "before we initiate the API" part, too

**Comment by patriciagarcia** [comment]
there is one here https://github.com/hoodiehq/pouchdb-hoodie-api/commit/993c1a9ec880a82b4d29eca52fb02dac851eec40 :)

**Comment by gr2m** [comment]
closed via https://github.com/hoodiehq/pouchdb-hoodie-api/pull/34
