### ISSUE TITLE
run docs & deploydocs in postpublish

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/pouchdb-hoodie-api#38]
doesn't seem to happen right now, does it?

**Comment by lewiscowper** [comment]
I'm not sure if it's in postpublish, but any build that goes through travis on master will deploy the docs. It all happens in the `.travis.yml` file as opposed to the package.json though, see:

https://github.com/hoodiehq/pouchdb-hoodie-api/blob/master/.travis.yml#L25-L27

**Comment by gr2m** [comment]
ahhh great catch, I haven't seen this, thanks @lewiscowper!
