### ISSUE TITLE
add .clear() method

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/pouchdb-hoodie-api#39]
follow up for #31 

We left out `api.clear()` from the scope of this plugin initially because we thought we wouldn't add events. `api.clear()` is just like `api.removeAll()`, but without triggering the `add`, `update`, `remove` and `change` events.

It shouldn't be exposed for [Modular Usage](https://github.com/hoodiehq/pouchdb-hoodie-api#modular-usage), just like `on`, `one` and `off`

**UPDATE** also add `clear` event, that only gets called when `api.clear()` gets called and it finishes successfully

**Comment by HipsterBrown** [comment]
@gr2m by "follow up", you mean after #31 has been merged, correct?

**Comment by gr2m** [comment]
yes, exactly, it kind of depends on #31, that's why I added it

**Comment by patriciagarcia** [comment]
@gr2m, I am not sure this is compatible with the current implementation of events. In #31, I am using PouchDB events and afaik there is no way to stop PouchDB events from being triggered when you delete docs. The only operation I can find that won't trigger the events is [destroying the db](http://pouchdb.com/api.html#events).

Maybe we need to rethink the whole events implementation if `clear` is needed?

**Comment by gr2m** [comment]
destroying the db sounds right to me for `.clear()`. You'd call clear for example when you sign out of an account, you'd want to remove everything in the database and start with a clear state. Anything speaking against destroying the db on clear?

**Comment by gr2m** [comment]
@nolanlawson if I remember correctly, there is some known issue with `db.destroy()`, right? I'd love to hear your thoughts on adding a `store.clear()` method that wouldn't trigger the `delete` events on objects, if you have a moment

**Comment by nolanlawson** [comment]
@gr2m Long-term, both `destroy()` and calling `remove()` for all documents should be stable, but in practice there are lots of issues with `destroy()` due to race conditions in different implementations of IndexedDB. I'm hoping most of those will be ironed out once I (or someone) have implemented native secondary indexes, which are the source of most of those race conditions.

**Comment by gr2m** [comment]
thanks @nolanlawson! What would you recommend for the time being? Should we silently delete all docs and do not call `db.destroy()` at all?

**Comment by toh82** [comment]
Orrr, donno how to link issues with PRs ^^, so here is it 
https://github.com/hoodiehq/pouchdb-hoodie-api/pull/50

**Comment by gr2m** [comment]
@toh82 add a `closes #39` to the description of the PR. Once it gets merged, the related issue will be closed automagically :)

**Comment by gr2m** [comment]
fixed via https://github.com/hoodiehq/pouchdb-hoodie-api/issues/50
