### ISSUE TITLE
.findAll() should not return design docs

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/pouchdb-hoodie-api#46]
it's a store API, meant only to interact with objects stored in it. CouchDB design docs is an implementation detail that we should not expose.

So by default, I'd vote that at least the `*All` methods like `findAll` should ignore design docs.

Any thoughts?

**Comment by zoepage** [comment]
+1

**Comment by janl** [comment]
do they take options, so people can opt into getting ddocs?

**Comment by gr2m** [comment]
If people want ddocs, they can still use the PouchDB instance that we expose at `store.db`. I think the API is just fine: `store.db.get(ddocid)`

**Comment by janl** [comment]
perfect.

**Comment by NickColley** [comment]
I'm going to have a go fixing this bug fyi :penguin:

**Comment by gr2m** [comment]
fixed via  https://github.com/hoodiehq/pouchdb-hoodie-api/issues/60
