### ISSUE TITLE
missing curly braces

### ISSUE THREAD

**Issue by janl** [hoodiehq/pouchdb-hoodie-api#51]
https://github.com/hoodiehq/pouchdb-hoodie-api/blob/master/utils/to-object.js#L6 nasty!

**Comment by gr2m** [comment]
We only do this for return statments, where it's perfectly fine. It's much more read able.

**Comment by gr2m** [comment]
sorry didn't meant to close it :)

**Comment by toh82** [comment]
Don't want to be to loud, since i'm a new here, but for me letting out the curlies looks like a bug. 
True, it's readable if you fammilar with it, but it's bit like fallthrough in switches, where you donno if it is an author mistake or wanted, hope you got me right.

**Comment by gr2m** [comment]
fixed via https://github.com/hoodiehq/pouchdb-hoodie-api/pull/52
