### ISSUE TITLE
.findOrAdd() should not trigger "add" event if object can be found

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/pouchdb-hoodie-api#58]

**Comment by NickColley** [comment]
Having a go at this one.

**Comment by NickColley** [comment]
Ok looks like there's a few ways this could be fixed.

Problem is that findOrAdd is wrapped by eventify but a find operation doesnt need to be wrapped.

My PR passes the API methods via the state so the findOrAdd is using the external API.

There's a few other ways it could be fixed but it's pretty dodge so lets talk about it?

**Comment by zoepage** [comment]
Doing some catch up...
Where is the PR? Is it merged or maybe closed?

Is your discussion somewhere to follow up? :)

**Comment by NickColley** [comment]
Hey Zoe,

Sorry I forgot to follow this up. :P

We had a discussion on Slack about this:

https://hoodie-community.slack.com/messages/hoodie-pouch/

(http://hood.ie/chat/ if future travellers want to join and read the converstation)

```
nick [10:22 PM] 
My PR techinically fixes the problem but I'm not happy with that

gregor [10:22 PM] 
it's not too much code

gregor [10:22 PM]
but we expose the methods separately, including findOrAdd

nick [10:22 PM] 
Make something explicit rather than magic?

nick [10:23 PM]
So you call the emitter manually?

gregor [10:23 PM] 
yes

gregor [10:23 PM]
It's the only method that is affected by it

gregor [10:23 PM]
maybe we can share some code between the findOrAdd method that can be exposed by itself and the one that triggers events, but I think we should implement it twice

gregor [10:24 PM]
more code, but it's not too bad I think.

gregor [10:24 PM]
yeah it's really a tough one

gregor [10:24 PM]
or: we don't expose it like the other APIs

gregor [10:24 PM]
so you can't do `require('pouchdb-hoodie-api/find-or-add')`

gregor [10:25 PM]
and only use it internally like the `.on`, `.off` methods
```

I think what I'm going to try is to change the eventify wrapper so we're not wrapping methods and explicitly call the event emitter within the relevant API methods.

@gr2m does that sound like a good way to go forwards?

**Comment by gr2m** [comment]
no, let's leave the emitter out of the separate methods. I wouldn't put the logic into all the methods just because of `findOrAdd`. I'd rather find a solution for `findOrAdd` only. Even if the soluition is to implement it twice, or to not expose it as separate method like `add` etc

**Comment by NickColley** [comment]
Fixed with https://github.com/hoodiehq/pouchdb-hoodie-api/pull/66
