### ISSUE TITLE
Use custom clone 

### ISSUE THREAD

**Issue by NickColley** [hoodiehq/pouchdb-hoodie-api#67]
PouchDB has replaced the extend usage with a custom clone, noticed pouchdb-extend is being used here.

@nolanlawson , is pouchdb-extend now going to use the new clone functionality or do we need to port it?

Context:
- https://github.com/hoodiehq/pouchdb-hoodie-api/blob/master/helpers/update-many.js#L3
- https://github.com/pouchdb/pouchdb/pull/4162/files

**Comment by nolanlawson** [comment]
We should probably export it in the extras API. I'm becoming more and more skeptical of hyper-modularity.

Our extend() is very tailored to our particular needs, though, so it might not exactly meet Hoodie's. E.g. we convert dates to strings, and we don't support IE <=9.

**Comment by NickColley** [comment]
I'm going to close this out since it's pre-optimizing. Thanks for your time @nolanlawson  :dancer: :+1:
